"""
arkhe.komodo.stub_generator
-------------------------------
Dynamic stub generator for IDE autocomplete support.

Generates .pyi stub files for decorated Komodo classes to enable
full IDE autocomplete and type hints for dynamically generated methods.

Key design decisions
--------------------
1. The stub is written next to the *caller's* source file, not inside the
   installed package.  PyCharm and Pylance index the project source tree, so
   a stub placed at ``src/practice01/HttpRequest.pyi`` will be found
   automatically without any extra IDE configuration.

2. Builder method return types are qualified as ``HttpRequest.Builder`` instead
   of the bare ``Builder``, which is required for Pylance/PyCharm to resolve
   the inner class correctly when the stub is read in isolation.

3. The unused ``Self`` import (which triggered an IDE warning) is emitted only
   when it is actually used in the stub body.
"""

import os
import sys
import inspect
from typing import Type, Dict, Set, List, Optional, Any
from pathlib import Path


class StubGenerator:
    """Generates .pyi stub files for Komodo-decorated classes."""

    def __init__(self, cls: Type):
        self.cls = cls
        self.module_name = cls.__module__
        self.class_name = cls.__name__
        self.fields: Dict[str, str] = self._extract_fields()
        self.defaults: Set[str] = self._extract_defaults()
        self.komodo_meta: Set[str] = getattr(cls, "__komodo_meta__", set())
        self.singulars: List[str] = getattr(cls, "__komodo_singulars__", [])

    # ------------------------------------------------------------------ #
    #  Introspection helpers                                               #
    # ------------------------------------------------------------------ #

    def _extract_fields(self) -> Dict[str, str]:
        fields = {}
        for name, annotation in getattr(self.cls, "__annotations__", {}).items():
            if not name.startswith("_"):
                fields[name] = self._annotation_to_str(annotation)
        return fields

    def _extract_defaults(self) -> Set[str]:
        defaults = set()
        for name in self.fields:
            if hasattr(self.cls, name):
                attr = getattr(self.cls, name)
                if not callable(attr):
                    defaults.add(name)
        return defaults

    @staticmethod
    def _annotation_to_str(annotation: Any) -> str:
        if annotation is None:
            return "None"
        if isinstance(annotation, str):
            return annotation
        if isinstance(annotation, type):
            if getattr(annotation, "__module__", None) == "builtins":
                return annotation.__qualname__
            mod = getattr(annotation, "__module__", "")
            qual = getattr(annotation, "__qualname__", annotation.__name__)
            return f"{mod}.{qual}" if mod else qual
        # typing generics: List[int], Dict[str, Any], etc.
        return str(annotation).replace("typing.", "")

    def _extract_item_type(self, list_annotation: str) -> str:
        if "[" in list_annotation and "]" in list_annotation:
            start = list_annotation.index("[") + 1
            end = list_annotation.rindex("]")
            return list_annotation[start:end].strip()
        return "Any"

    # ------------------------------------------------------------------ #
    #  Stub generation                                                     #
    # ------------------------------------------------------------------ #

    def generate_stub(self) -> str:
        """Return the complete .pyi stub as a string."""
        # Decide up-front whether Self is actually needed so we don't emit
        # an unused import that the IDE flags as a warning.
        uses_self = self._stub_uses_self()

        imports = [
            '"""',
            f"Type stubs for {self.class_name}",
            "",
            "Auto-generated by arkhe.komodo for IDE autocomplete support.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import Any, Dict, List, Optional",
        ]

        if uses_self:
            imports += [
                "from typing import TYPE_CHECKING",
                "",
                "if TYPE_CHECKING:",
                "    from typing_extensions import Self",
            ]

        imports.append("")

        lines = imports + [f"class {self.class_name}:"]

        # Field declarations
        for field_name, field_type in self.fields.items():
            lines.append(f"    {field_name}: {field_type}")
        if self.fields:
            lines.append("")

        # Generated method groups
        self._add_constructor_stubs(lines)
        self._add_repr_stubs(lines)
        self._add_eq_stubs(lines)
        self._add_builder_stubs(lines)
        self._add_logger_stubs(lines)
        self._add_accessor_stubs(lines)
        self._add_copyable_stubs(lines)
        self._add_serialization_stubs(lines)

        if lines[-1] != "":
            lines.append("")

        return "\n".join(lines)

    def _stub_uses_self(self) -> bool:
        """Return True if the generated stub body will reference Self."""
        has_copyable = "copyable" in self.komodo_meta or "data" in self.komodo_meta
        has_from_dict = "from_dict" in self.komodo_meta or "data" in self.komodo_meta
        has_json = "json" in self.komodo_meta or "data" in self.komodo_meta
        has_wither_accessors = (
            "accessors" in self.komodo_meta
            and any(hasattr(self.cls, f"with_{f}") for f in self.fields)
            and "builder" not in self.komodo_meta
        )
        return has_copyable or has_from_dict or has_json or has_wither_accessors

    # ------------------------------------------------------------------ #
    #  Per-feature stub sections                                           #
    # ------------------------------------------------------------------ #

    def _add_constructor_stubs(self, lines: List[str]) -> None:
        meta = self.komodo_meta
        has = any(k in meta for k in (
            "all_args_constructor", "required_args_constructor", "no_args_constructor",
            "data", "record",
        ))
        if not has:
            return

        args = ["self"]
        for field_name, field_type in self.fields.items():
            if field_name in self.defaults:
                args.append(f"{field_name}: {field_type} = ...")
            else:
                args.append(f"{field_name}: {field_type}")

        lines.append(f"    def __init__({', '.join(args)}) -> None: ...")
        lines.append("")

    def _add_repr_stubs(self, lines: List[str]) -> None:
        if "to_str" in self.komodo_meta or "data" in self.komodo_meta:
            lines.append("    def __repr__(self) -> str: ...")
            lines.append("    def __str__(self) -> str: ...")
            lines.append("")

    def _add_eq_stubs(self, lines: List[str]) -> None:
        if "eq" in self.komodo_meta or "data" in self.komodo_meta:
            lines.append("    def __eq__(self, other: object) -> bool: ...")
            lines.append("    def __hash__(self) -> int: ...")
            lines.append("")

    def _add_builder_stubs(self, lines: List[str]) -> None:
        if "builder" not in self.komodo_meta:
            return

        cn = self.class_name  # e.g. "HttpRequest"
        # FIX: qualify the return type as OuterClass.Builder so Pylance/PyCharm
        # can resolve it when reading the stub in isolation.
        builder_ret = f"{cn}.Builder"

        lines.append(f"    class Builder:")
        lines.append(f"        def __init__(self) -> None: ...")

        for field_name, field_type in self.fields.items():
            if field_name in self.singulars:
                singular = field_name[:-1] if field_name.endswith("s") else f"single_{field_name}"
                item_type = self._extract_item_type(field_type)
                lines.append(f"        def {singular}(self, item: {item_type}) -> {builder_ret}: ...")
                lines.append(f"        def {field_name}(self, value: {field_type}) -> {builder_ret}: ...")
            else:
                lines.append(f"        def with_{field_name}(self, value: {field_type}) -> {builder_ret}: ...")

        # build() return type: use a string forward-ref so it resolves to the
        # outer class without needing it to be in scope inside Builder.
        lines.append(f"        def build(self) -> {cn}: ...")
        lines.append("")

        lines.append(f"    @classmethod")
        lines.append(f"    def builder(cls) -> {builder_ret}: ...")
        lines.append("")

    def _add_logger_stubs(self, lines: List[str]) -> None:
        if "logger" in self.komodo_meta:
            lines.append("    import logging")
            lines.append("    logger: logging.Logger")
            lines.append("")

    def _add_accessor_stubs(self, lines: List[str]) -> None:
        if "accessors" not in self.komodo_meta:
            return

        added = False
        for field_name, field_type in self.fields.items():
            if hasattr(self.cls, f"get_{field_name}"):
                lines.append(f"    def get_{field_name}(self) -> {field_type}: ...")
                added = True
            if hasattr(self.cls, f"set_{field_name}"):
                lines.append(f"    def set_{field_name}(self, value: {field_type}) -> None: ...")
                added = True
            if hasattr(self.cls, f"with_{field_name}") and "builder" not in self.komodo_meta:
                lines.append(f"    def with_{field_name}(self, value: {field_type}) -> Self: ...")
                added = True
        if added:
            lines.append("")

    def _add_copyable_stubs(self, lines: List[str]) -> None:
        if "copyable" not in self.komodo_meta and "data" not in self.komodo_meta:
            return

        lines.append("    def copy(self) -> Self: ...")
        kwargs_parts = [f"{n}: {t} = ..." for n, t in self.fields.items()]
        lines.append(f"    def copy_with(self, {', '.join(kwargs_parts)}) -> Self: ...")
        lines.append("")

    def _add_serialization_stubs(self, lines: List[str]) -> None:
        meta = self.komodo_meta
        has_to_dict  = "to_dict"   in meta or "data" in meta
        has_from_dict= "from_dict" in meta or "data" in meta
        has_json     = "json"      in meta or "data" in meta

        if has_to_dict:
            lines.append("    def to_dict(self) -> Dict[str, Any]: ...")
        if has_from_dict:
            lines.append("    @classmethod")
            lines.append("    def from_dict(cls, data: Dict[str, Any]) -> Self: ...")
        if has_json:
            lines.append("    def to_json(self) -> str: ...")
            lines.append("    @classmethod")
            lines.append("    def from_json(cls, data: str) -> Self: ...")
        if has_to_dict or has_from_dict or has_json:
            lines.append("")


# --------------------------------------------------------------------------- #
#  File-writing helpers                                                        #
# --------------------------------------------------------------------------- #

def _resolve_output_dir(cls: Type) -> str:
    """
    Return the directory where the stub should be written.

    Priority:
    1. The directory of the *source file* of the module that defines the class
       (i.e. the caller's .py file).  This is what IDEs index.
    2. Current working directory as a fallback.

    We deliberately do NOT fall back to the installed package directory
    (inside .venv) because IDEs don't always watch that path for changes.
    """
    module = sys.modules.get(cls.__module__)
    if module:
        src_file = getattr(module, "__file__", None)
        if src_file:
            return os.path.dirname(os.path.abspath(src_file))
    return os.getcwd()


def generate_and_write_stub(cls: Type, output_dir: Optional[str] = None) -> str:
    """
    Generate and write a .pyi stub file for a Komodo-decorated class.

    The stub is placed next to the source file that *defines* the class so
    PyCharm and Pylance pick it up automatically without extra configuration.

    Args:
        cls:        The decorated class.
        output_dir: Override the output directory.  Defaults to the directory
                    of the module that defines the class.

    Returns:
        Absolute path to the written .pyi file.
    """
    generator = StubGenerator(cls)
    stub_content = generator.generate_stub()

    if output_dir is None:
        output_dir = _resolve_output_dir(cls)

    stub_path = os.path.join(output_dir, f"{cls.__name__}.pyi")
    Path(stub_path).parent.mkdir(parents=True, exist_ok=True)
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write(stub_content)

    return stub_path


def install_stubs_on_class(cls: Type) -> None:
    """Convenience wrapper — silently generates and writes a stub."""
    try:
        generate_and_write_stub(cls)
    except Exception:
        pass


__all__ = ["StubGenerator", "generate_and_write_stub", "install_stubs_on_class"]
